--------------------------------------------------------
-- Archivo creado  - viernes-abril-07-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ATTACHED_FILE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."ATTACHED_FILE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CAMPAIGN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."CAMPAIGN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CAT_VIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."CAT_VIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLASSIFICATION_CAMPAIGNS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."CLASSIFICATION_CAMPAIGNS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLASSIFICATION_USERS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."CLASSIFICATION_USERS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPANY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."COMPANY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FUNCTIONALITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."FUNCTIONALITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROFILE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."PROFILE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PUBLICATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."PUBLICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PUBLICATION_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."PUBLICATION_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPORT_MOVEMENTS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."REPORT_MOVEMENTS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOLINF"."USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAT_CLASSIFICATION_CAMPAIGNS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" 
   (	"CLASSIFICATION_CAMPAIGN_ID" NUMBER(10,0), 
	"PARENT_CLASSIFICATION_ID" NUMBER(10,0), 
	"FK_COMPANY" NUMBER(10,0), 
	"FK_VIEW" NUMBER(10,0), 
	"CLASS_NAME" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR), 
	"LEVEL_CCC" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_CLASSIFICATION_USERS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" 
   (	"CAT_CLASSIFICATION_USERS_ID" NUMBER(10,0), 
	"PARENT_CLASSIFICATION_ID" NUMBER(10,0), 
	"FK_COMPANY" NUMBER(10,0), 
	"FK_VIEW" NUMBER(10,0), 
	"CLASS_NAME" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_CLIENT
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_CLIENT" 
   (	"ID_COMPANY" NUMBER(10,0), 
	"NAME" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_FUNCTIONALITIES
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_FUNCTIONALITIES" 
   (	"FUNCTIONALITY_ID" NUMBER(10,0), 
	"FUNCTIONALITY_CODE" VARCHAR2(20 CHAR), 
	"NAME" VARCHAR2(80 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_PROFILES
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_PROFILES" 
   (	"PROFILE_ID" NUMBER(10,0), 
	"PROFILE" VARCHAR2(50 CHAR), 
	"COMMENTS" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_PUBLICATIONS_TYPE
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_PUBLICATIONS_TYPE" 
   (	"PUBLICATION_TYPE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT_VIEWS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."CAT_VIEWS" 
   (	"CAT_VIEW_ID" NUMBER(10,0), 
	"COLORS" VARCHAR2(100 CHAR), 
	"LOGOS" VARCHAR2(300 CHAR), 
	"MESSAGES" VARCHAR2(300 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REL_PROFILE_FUNCTIONALITY
--------------------------------------------------------

  CREATE TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" 
   (	"FUNCTIONALITY_ID" NUMBER(10,0), 
	"PROFILE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REL_USERS_CLASSIFICATION
--------------------------------------------------------

  CREATE TABLE "BOLINF"."REL_USERS_CLASSIFICATION" 
   (	"CLASSIFICATION_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ATTACHED_FILES
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_ATTACHED_FILES" 
   (	"ATTACHED_FILE_ID" NUMBER(10,0), 
	"FK_PUBLICATION" NUMBER(10,0), 
	"IS_PUBLIC" NUMBER(3,0) DEFAULT '0', 
	"FILE_NAME" VARCHAR2(100 CHAR), 
	"FILE_PATH" VARCHAR2(45 CHAR), 
	"FILE_EXTENSION" VARCHAR2(45 CHAR), 
	"FK_CAMPAIGN" NUMBER(10,0), 
	"IS_ACUSE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CAMPAIGNS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_CAMPAIGNS" 
   (	"CAMPAIGN_ID" NUMBER(10,0), 
	"FK_COMPANY" NUMBER(10,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CAMPAIGN_NAME" VARCHAR2(150 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR), 
	"FK_CAT_CLASSIFICATION" NUMBER(10,0), 
	"IMAGE_FILE_PATH" VARCHAR2(45 CHAR), 
	"EXCEL_FILE_PATH" VARCHAR2(45 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_PUBLICATIONS" 
   (	"PUBLICATION_ID" NUMBER(10,0), 
	"FK_CAMPAIGN" NUMBER(10,0), 
	"FK_PUBLICATION_TYPE" NUMBER(10,0), 
	"PUBLISHED_DATE" DATE, 
	"NAME" VARCHAR2(45 CHAR), 
	"TEMPLATE_FILE_PATH" VARCHAR2(45 CHAR), 
	"DATA_FILE_PATH" VARCHAR2(45 CHAR), 
	"DATA_FILE_PAGE" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(150 CHAR), 
	"IS_ENABLE" NUMBER(3,0) DEFAULT '0', 
	"IMAGE_FILE_PATH" VARCHAR2(45 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_REPORT_MOVEMENTS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_REPORT_MOVEMENTS" 
   (	"REPORT_MOVEMENTS_ID" NUMBER(10,0), 
	"FK_CAMPAIGN" NUMBER(10,0), 
	"FK_USER" NUMBER(10,0), 
	"RM_DATE" DATE, 
	"ID_STARS" VARCHAR2(20 BYTE), 
	"PUESTO_EN_STARS" VARCHAR2(30 BYTE), 
	"EMPLOYEE_NAME" VARCHAR2(50 BYTE), 
	"SIVALE_NAME" VARCHAR2(50 BYTE), 
	"CARD_NUMBER" VARCHAR2(16 BYTE), 
	"BID" VARCHAR2(5 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(30 BYTE), 
	"MONTO" NUMBER(9,0), 
	"MOVEMENTS" VARCHAR2(50 BYTE), 
	"OBSERVACIONES" VARCHAR2(200 BYTE), 
	"MONTH" VARCHAR2(50 BYTE), 
	"YEAR" NUMBER(5,0), 
	"COMPANIA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USER_DATA
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_USER_DATA" 
   (	"PUBLICATION_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"DATA" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USER_DATA_C
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_USER_DATA_C" 
   (	"CAMPAIGN_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USERS
--------------------------------------------------------

  CREATE TABLE "BOLINF"."T_USERS" 
   (	"USER_ID" NUMBER(10,0), 
	"FK_COMPANY" NUMBER(10,0), 
	"FK_PROFILE" NUMBER(10,0), 
	"USER_LOGIN" VARCHAR2(45 CHAR), 
	"PASSWORD" VARCHAR2(45 CHAR), 
	"EMAIL" VARCHAR2(45 CHAR), 
	"FULL_NAME" VARCHAR2(100 CHAR), 
	"FIRST_NAME" VARCHAR2(45 CHAR), 
	"LAST_NAME_1" VARCHAR2(45 CHAR), 
	"LAST_NAME_2" VARCHAR2(45 CHAR), 
	"TJ_CARD_NUMBER" VARCHAR2(45 CHAR), 
	"TJ_ACCOUNT_NUMBER" VARCHAR2(45 CHAR), 
	"TJ_EMPLOYER" VARCHAR2(45 CHAR), 
	"TJ_ORIGIN" VARCHAR2(45 CHAR), 
	"TJ_CARD_TYPE" VARCHAR2(45 CHAR), 
	"TJ_PRODUCT" VARCHAR2(45 CHAR), 
	"TJ_REFERENCE" VARCHAR2(45 CHAR), 
	"TJ_ACCOUNT_STATUS" VARCHAR2(45 CHAR), 
	"TJ_CARD_STATUS" VARCHAR2(45 CHAR), 
	"TJ_BID" VARCHAR2(20 CHAR), 
	"TJ_RAZON_SOCIAL" VARCHAR2(50 CHAR), 
	"TJ_STARS" VARCHAR2(30 CHAR), 
	"TJ_ECAPS" VARCHAR2(30 CHAR), 
	"TJ_IDENTIFICACION" NUMBER(3,0), 
	"TJ_ACUSE_FORD_LINCOLN" NUMBER(3,0), 
	"TJ_INSCRITO_EN_PROGRAMA" NUMBER(3,0), 
	"TJ_ACUSE_FORD_CREDIT" NUMBER(3,0), 
	"TJ_CARTA_DOBLE_PERFIL" NUMBER(3,0), 
	"TJ_COMENTARIOS" VARCHAR2(200 CHAR), 
	"TJ_ESTATUS_GENERAL" VARCHAR2(50 CHAR), 
	"TJ_CODIGO_PROCEDENCIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View REL_USER_CAMPAIGN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BOLINF"."REL_USER_CAMPAIGN" ("USER_ID", "CAMPAIGN_ID") AS 
  SELECT 
        T_USER_DATA.USER_ID, T_CAMPAIGNS.CAMPAIGN_ID
    FROM
        T_USER_DATA 
            INNER JOIN
        T_PUBLICATIONS ON T_USER_DATA.PUBLICATION_ID = T_PUBLICATIONS.PUBLICATION_ID
            INNER JOIN
        T_CAMPAIGNS  ON T_PUBLICATIONS.FK_CAMPAIGN = T_CAMPAIGNS.CAMPAIGN_ID;
--------------------------------------------------------
--  DDL for Index FK_CAMPAIGN_REPORT
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAMPAIGN_REPORT" ON "BOLINF"."T_REPORT_MOVEMENTS" ("FK_CAMPAIGN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION_CAMPAIGN
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION_CAMPAIGN" ON "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("PARENT_CLASSIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION_CAMPAI_1
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION_CAMPAI_1" ON "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("FK_VIEW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION_USERS_CA
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION_USERS_CA" ON "BOLINF"."CAT_CLASSIFICATION_USERS" ("PARENT_CLASSIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION_USERS__1
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION_USERS__1" ON "BOLINF"."CAT_CLASSIFICATION_USERS" ("FK_VIEW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION1_CAMPAIG
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION1_CAMPAIG" ON "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("FK_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_CAT_CLASSIFICATION1_USERS_T
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_CAT_CLASSIFICATION1_USERS_T" ON "BOLINF"."CAT_CLASSIFICATION_USERS" ("FK_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_REL_PROFILE_FUNCTIONALITY_C
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_REL_PROFILE_FUNCTIONALITY_C" ON "BOLINF"."REL_PROFILE_FUNCTIONALITY" ("FUNCTIONALITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_REL_PROFILE_FUNCTIONALITY_1
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_REL_PROFILE_FUNCTIONALITY_1" ON "BOLINF"."REL_PROFILE_FUNCTIONALITY" ("PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_REL_USERS_CLASSIFICATION_T_
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_REL_USERS_CLASSIFICATION_T_" ON "BOLINF"."REL_USERS_CLASSIFICATION" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_ATTACHED_FILES_T_NOTIFICA
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_ATTACHED_FILES_T_NOTIFICA" ON "BOLINF"."T_ATTACHED_FILES" ("FK_PUBLICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_CAMPAIGNS_CAT_CLASSIFICAT
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_CAMPAIGNS_CAT_CLASSIFICAT" ON "BOLINF"."T_CAMPAIGNS" ("FK_CAT_CLASSIFICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_CAMPAIGNS_T_COMPANIES1_ID
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_CAMPAIGNS_T_COMPANIES1_ID" ON "BOLINF"."T_CAMPAIGNS" ("FK_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_NOTIFICATIONS_T_CAMPAIGNS
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_NOTIFICATIONS_T_CAMPAIGNS" ON "BOLINF"."T_PUBLICATIONS" ("FK_CAMPAIGN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_PUBLICATIONS_CAT_PUBLICAT
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_PUBLICATIONS_CAT_PUBLICAT" ON "BOLINF"."T_PUBLICATIONS" ("FK_PUBLICATION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_PUBLICATIONS_HAS_T_USERS_
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_PUBLICATIONS_HAS_T_USERS_" ON "BOLINF"."T_USER_DATA" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_PUBLICATIONS_HAS_T_USER_1
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_PUBLICATIONS_HAS_T_USER_1" ON "BOLINF"."T_USER_DATA" ("PUBLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_USERS_CAT_PROFILES1_IDX
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_USERS_CAT_PROFILES1_IDX" ON "BOLINF"."T_USERS" ("FK_PROFILE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_T_USERS_T_COMPANIES1_IDX
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_T_USERS_T_COMPANIES1_IDX" ON "BOLINF"."T_USERS" ("FK_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FK_USER_REPORT
--------------------------------------------------------

  CREATE INDEX "BOLINF"."FK_USER_REPORT" ON "BOLINF"."T_REPORT_MOVEMENTS" ("FK_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."NAME_UNIQUE" ON "BOLINF"."CAT_PUBLICATIONS_TYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY" ON "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("CLASSIFICATION_CAMPAIGN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_1" ON "BOLINF"."T_CAMPAIGNS" ("CAMPAIGN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_10
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_10" ON "BOLINF"."REL_USERS_CLASSIFICATION" ("CLASSIFICATION_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_11
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_11" ON "BOLINF"."CAT_VIEWS" ("CAT_VIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_12
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_12" ON "BOLINF"."CAT_CLASSIFICATION_USERS" ("CAT_CLASSIFICATION_USERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_13
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_13" ON "BOLINF"."CAT_FUNCTIONALITIES" ("FUNCTIONALITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_2" ON "BOLINF"."CAT_CLIENT" ("ID_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_3" ON "BOLINF"."T_USER_DATA" ("PUBLICATION_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_4
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_4" ON "BOLINF"."T_ATTACHED_FILES" ("ATTACHED_FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_5
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_5" ON "BOLINF"."T_PUBLICATIONS" ("PUBLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_6
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_6" ON "BOLINF"."CAT_PUBLICATIONS_TYPE" ("PUBLICATION_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_7
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_7" ON "BOLINF"."CAT_PROFILES" ("PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_8
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_8" ON "BOLINF"."T_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_9
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."PRIMARY_9" ON "BOLINF"."REL_PROFILE_FUNCTIONALITY" ("FUNCTIONALITY_ID", "PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TJ_ACCOUNT_NUMBER_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."TJ_ACCOUNT_NUMBER_UNIQUE" ON "BOLINF"."T_USERS" ("TJ_ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_REPORT_MOVEMENTS__ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOLINF"."T_REPORT_MOVEMENTS__ID" ON "BOLINF"."T_REPORT_MOVEMENTS" ("REPORT_MOVEMENTS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CAT_CLASSIFICATION_CAMPAIGNS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("CLASSIFICATION_CAMPAIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" MODIFY ("LEVEL_CCC" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" MODIFY ("FK_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" MODIFY ("CLASSIFICATION_CAMPAIGN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_CLASSIFICATION_USERS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" ADD CONSTRAINT "PRIMARY_12" PRIMARY KEY ("CAT_CLASSIFICATION_USERS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" MODIFY ("FK_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" MODIFY ("CAT_CLASSIFICATION_USERS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_CLIENT
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_CLIENT" ADD CONSTRAINT "PRIMARY_2" PRIMARY KEY ("ID_COMPANY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLIENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_CLIENT" MODIFY ("ID_COMPANY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_FUNCTIONALITIES
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_FUNCTIONALITIES" ADD CONSTRAINT "PRIMARY_13" PRIMARY KEY ("FUNCTIONALITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_FUNCTIONALITIES" MODIFY ("FUNCTIONALITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_PROFILES
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_PROFILES" ADD CONSTRAINT "PRIMARY_7" PRIMARY KEY ("PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_PROFILES" MODIFY ("PROFILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_PUBLICATIONS_TYPE
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_PUBLICATIONS_TYPE" ADD CONSTRAINT "NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_PUBLICATIONS_TYPE" ADD CONSTRAINT "PRIMARY_6" PRIMARY KEY ("PUBLICATION_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_PUBLICATIONS_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."CAT_PUBLICATIONS_TYPE" MODIFY ("PUBLICATION_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_VIEWS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_VIEWS" ADD CONSTRAINT "PRIMARY_11" PRIMARY KEY ("CAT_VIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."CAT_VIEWS" MODIFY ("CAT_VIEW_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REL_PROFILE_FUNCTIONALITY
--------------------------------------------------------

  ALTER TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" ADD CONSTRAINT "PRIMARY_9" PRIMARY KEY ("FUNCTIONALITY_ID", "PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" MODIFY ("PROFILE_ID" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" MODIFY ("FUNCTIONALITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REL_USERS_CLASSIFICATION
--------------------------------------------------------

  ALTER TABLE "BOLINF"."REL_USERS_CLASSIFICATION" ADD CONSTRAINT "PRIMARY_10" PRIMARY KEY ("CLASSIFICATION_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."REL_USERS_CLASSIFICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."REL_USERS_CLASSIFICATION" MODIFY ("CLASSIFICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ATTACHED_FILES
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_ATTACHED_FILES" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("ATTACHED_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_ATTACHED_FILES" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_ATTACHED_FILES" MODIFY ("ATTACHED_FILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_CAMPAIGNS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_CAMPAIGNS" ADD CONSTRAINT "PRIMARY_1" PRIMARY KEY ("CAMPAIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_CAMPAIGNS" MODIFY ("FK_CAT_CLASSIFICATION" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_CAMPAIGNS" MODIFY ("FK_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_CAMPAIGNS" MODIFY ("CAMPAIGN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_PUBLICATIONS" ADD CONSTRAINT "PRIMARY_5" PRIMARY KEY ("PUBLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_PUBLICATIONS" MODIFY ("IS_ENABLE" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_PUBLICATIONS" MODIFY ("FK_PUBLICATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_PUBLICATIONS" MODIFY ("FK_CAMPAIGN" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_PUBLICATIONS" MODIFY ("PUBLICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_REPORT_MOVEMENTS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_REPORT_MOVEMENTS" MODIFY ("REPORT_MOVEMENTS_ID" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_REPORT_MOVEMENTS" MODIFY ("FK_CAMPAIGN" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_REPORT_MOVEMENTS" ADD CONSTRAINT "T_REPORT_MOVEMENTS_PK" PRIMARY KEY ("REPORT_MOVEMENTS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_USER_DATA
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USER_DATA" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("PUBLICATION_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_USER_DATA" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USER_DATA" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USER_DATA" MODIFY ("PUBLICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_USER_DATA_C
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USER_DATA_C" MODIFY ("CAMPAIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USER_DATA_C" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_USERS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USERS" ADD CONSTRAINT "TJ_ACCOUNT_NUMBER_UNIQUE" UNIQUE ("TJ_ACCOUNT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_USERS" ADD CONSTRAINT "PRIMARY_8" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOLINF"."T_USERS" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USERS" MODIFY ("FK_PROFILE" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USERS" MODIFY ("FK_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BOLINF"."T_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CAT_CLASSIFICATION_CAMPAIGNS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ADD CONSTRAINT "FK_CCC_CAT_CLAS_CAMP" FOREIGN KEY ("PARENT_CLASSIFICATION_ID")
	  REFERENCES "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("CLASSIFICATION_CAMPAIGN_ID") ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ADD CONSTRAINT "FK_CCC_CAT_VIEWS" FOREIGN KEY ("FK_VIEW")
	  REFERENCES "BOLINF"."CAT_VIEWS" ("CAT_VIEW_ID") ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ADD CONSTRAINT "FK_CCC_TCOMPANIES" FOREIGN KEY ("FK_COMPANY")
	  REFERENCES "BOLINF"."CAT_CLIENT" ("ID_COMPANY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAT_CLASSIFICATION_USERS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" ADD CONSTRAINT "FK_CCU_CAT_CLAS_USERS" FOREIGN KEY ("PARENT_CLASSIFICATION_ID")
	  REFERENCES "BOLINF"."CAT_CLASSIFICATION_USERS" ("CAT_CLASSIFICATION_USERS_ID") ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" ADD CONSTRAINT "FK_CCU_CAT_VIEWS" FOREIGN KEY ("FK_VIEW")
	  REFERENCES "BOLINF"."CAT_VIEWS" ("CAT_VIEW_ID") ENABLE;
  ALTER TABLE "BOLINF"."CAT_CLASSIFICATION_USERS" ADD CONSTRAINT "FK_CCU_TCOMPANIES" FOREIGN KEY ("FK_COMPANY")
	  REFERENCES "BOLINF"."CAT_CLIENT" ("ID_COMPANY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REL_PROFILE_FUNCTIONALITY
--------------------------------------------------------

  ALTER TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" ADD CONSTRAINT "FK_RPF_CAT_FUNCTIO" FOREIGN KEY ("FUNCTIONALITY_ID")
	  REFERENCES "BOLINF"."CAT_FUNCTIONALITIES" ("FUNCTIONALITY_ID") ENABLE;
  ALTER TABLE "BOLINF"."REL_PROFILE_FUNCTIONALITY" ADD CONSTRAINT "FK_RPF_CAT_PROFILES" FOREIGN KEY ("PROFILE_ID")
	  REFERENCES "BOLINF"."CAT_PROFILES" ("PROFILE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REL_USERS_CLASSIFICATION
--------------------------------------------------------

  ALTER TABLE "BOLINF"."REL_USERS_CLASSIFICATION" ADD CONSTRAINT "FK_RUC_CAT_CLASS_USERS" FOREIGN KEY ("CLASSIFICATION_ID")
	  REFERENCES "BOLINF"."CAT_CLASSIFICATION_USERS" ("CAT_CLASSIFICATION_USERS_ID") ENABLE;
  ALTER TABLE "BOLINF"."REL_USERS_CLASSIFICATION" ADD CONSTRAINT "FK_RUC_T_USERS" FOREIGN KEY ("USER_ID")
	  REFERENCES "BOLINF"."T_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ATTACHED_FILES
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_ATTACHED_FILES" ADD CONSTRAINT "FK_TAF_CAMPAIGNS" FOREIGN KEY ("FK_CAMPAIGN")
	  REFERENCES "BOLINF"."T_CAMPAIGNS" ("CAMPAIGN_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOLINF"."T_ATTACHED_FILES" ADD CONSTRAINT "FK_TAF_TPUBLICATIONS" FOREIGN KEY ("FK_PUBLICATION")
	  REFERENCES "BOLINF"."T_PUBLICATIONS" ("PUBLICATION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_CAMPAIGNS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_CAMPAIGNS" ADD CONSTRAINT "FK_TC_CAT_CLAS_CAMP" FOREIGN KEY ("FK_CAT_CLASSIFICATION")
	  REFERENCES "BOLINF"."CAT_CLASSIFICATION_CAMPAIGNS" ("CLASSIFICATION_CAMPAIGN_ID") ENABLE;
  ALTER TABLE "BOLINF"."T_CAMPAIGNS" ADD CONSTRAINT "FK_TC_TCOMPANIES" FOREIGN KEY ("FK_COMPANY")
	  REFERENCES "BOLINF"."CAT_CLIENT" ("ID_COMPANY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_PUBLICATIONS" ADD CONSTRAINT "FK_TP_CAT_PUBLICAT_TYPE" FOREIGN KEY ("FK_PUBLICATION_TYPE")
	  REFERENCES "BOLINF"."CAT_PUBLICATIONS_TYPE" ("PUBLICATION_TYPE_ID") ENABLE;
  ALTER TABLE "BOLINF"."T_PUBLICATIONS" ADD CONSTRAINT "FK_TP_TCAMPAIGNS" FOREIGN KEY ("FK_CAMPAIGN")
	  REFERENCES "BOLINF"."T_CAMPAIGNS" ("CAMPAIGN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_REPORT_MOVEMENTS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_REPORT_MOVEMENTS" ADD CONSTRAINT "REPORT_MOV_T_CAMPAIGNS_FK" FOREIGN KEY ("FK_CAMPAIGN")
	  REFERENCES "BOLINF"."T_CAMPAIGNS" ("CAMPAIGN_ID") ENABLE;
  ALTER TABLE "BOLINF"."T_REPORT_MOVEMENTS" ADD CONSTRAINT "REPORT_MOV_T_USERS_FK" FOREIGN KEY ("FK_USER")
	  REFERENCES "BOLINF"."T_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USER_DATA
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USER_DATA" ADD CONSTRAINT "FK_TPUBLICATIONS" FOREIGN KEY ("PUBLICATION_ID")
	  REFERENCES "BOLINF"."T_PUBLICATIONS" ("PUBLICATION_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOLINF"."T_USER_DATA" ADD CONSTRAINT "FK_TUSERS" FOREIGN KEY ("USER_ID")
	  REFERENCES "BOLINF"."T_USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USER_DATA_C
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USER_DATA_C" ADD CONSTRAINT "T_USER_DATA_C_T_CAMPAIGNS_FK" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "BOLINF"."T_CAMPAIGNS" ("CAMPAIGN_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOLINF"."T_USER_DATA_C" ADD CONSTRAINT "T_USER_DATA_C_T_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "BOLINF"."T_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USERS
--------------------------------------------------------

  ALTER TABLE "BOLINF"."T_USERS" ADD CONSTRAINT "FK_TU_CAT_PROFILES" FOREIGN KEY ("FK_PROFILE")
	  REFERENCES "BOLINF"."CAT_PROFILES" ("PROFILE_ID") ENABLE;
  ALTER TABLE "BOLINF"."T_USERS" ADD CONSTRAINT "FK_TU_TCOMPANIES" FOREIGN KEY ("FK_COMPANY")
	  REFERENCES "BOLINF"."CAT_CLIENT" ("ID_COMPANY") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ATTACHED_FILE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."ATTACHED_FILE_ID_TRG" BEFORE
  INSERT ON BOLINF.T_ATTACHED_FILES FOR EACH ROW     WHEN (NEW.ATTACHED_FILE_ID IS NULL) BEGIN :NEW.ATTACHED_FILE_ID := BOLINF.ATTACHED_FILE_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."ATTACHED_FILE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAT_FUNCTIONALITIES_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."CAT_FUNCTIONALITIES_ID_TRG" BEFORE
  INSERT ON BOLINF.CAT_FUNCTIONALITIES FOR EACH ROW     WHEN (NEW.FUNCTIONALITY_ID IS NULL) BEGIN :NEW.FUNCTIONALITY_ID := BOLINF.FUNCTIONALITY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."CAT_FUNCTIONALITIES_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAT_PROFILES_PROFILE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."CAT_PROFILES_PROFILE_ID_TRG" BEFORE
  INSERT ON  CAT_PROFILES FOR EACH ROW        WHEN (NEW.PROFILE_ID IS NULL) BEGIN :NEW.PROFILE_ID :=  PROFILE_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."CAT_PROFILES_PROFILE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAT_VIEWS_CAT_VIEW_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."CAT_VIEWS_CAT_VIEW_ID_TRG" BEFORE
  INSERT ON  CAT_VIEWS FOR EACH ROW        WHEN (NEW.CAT_VIEW_ID IS NULL) BEGIN :NEW.CAT_VIEW_ID :=  CAT_VIEW_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."CAT_VIEWS_CAT_VIEW_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLASSIFICATION_CAMPAIGN_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."CLASSIFICATION_CAMPAIGN_ID_TRG" BEFORE
  INSERT ON BOLINF.CAT_CLASSIFICATION_CAMPAIGNS FOR EACH ROW     WHEN (NEW.CLASSIFICATION_CAMPAIGN_ID IS NULL) BEGIN :NEW.CLASSIFICATION_CAMPAIGN_ID := BOLINF.CLASSIFICATION_CAMPAIGNS_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."CLASSIFICATION_CAMPAIGN_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLASSIFICATION_USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."CLASSIFICATION_USERS_TRG" BEFORE
  INSERT ON BOLINF.CAT_CLASSIFICATION_USERS FOR EACH ROW     WHEN (NEW.CAT_CLASSIFICATION_USERS_ID IS NULL) BEGIN :NEW.CAT_CLASSIFICATION_USERS_ID := BOLINF.CLASSIFICATION_USERS_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."CLASSIFICATION_USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PUBLICATION_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."PUBLICATION_ID_TRG" BEFORE
  INSERT ON BOLINF.T_PUBLICATIONS FOR EACH ROW     WHEN (NEW.PUBLICATION_ID IS NULL) BEGIN :NEW.PUBLICATION_ID := BOLINF.PUBLICATION_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."PUBLICATION_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PUBLICATION_TYPE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."PUBLICATION_TYPE_ID_TRG" BEFORE
  INSERT ON BOLINF.CAT_PUBLICATIONS_TYPE FOR EACH ROW     WHEN (NEW.PUBLICATION_TYPE_ID IS NULL) BEGIN :NEW.PUBLICATION_TYPE_ID := BOLINF.PUBLICATION_TYPE_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."PUBLICATION_TYPE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REPORT_MOVEMENTS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."REPORT_MOVEMENTS_ID_TRG" BEFORE
  INSERT ON T_REPORT_MOVEMENTS FOR EACH ROW     WHEN (NEW.REPORT_MOVEMENTS_ID IS NULL) BEGIN :NEW.REPORT_MOVEMENTS_ID := REPORT_MOVEMENTS_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."REPORT_MOVEMENTS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CAMPAIGNS_CAMPAIGN_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."T_CAMPAIGNS_CAMPAIGN_ID_TRG" BEFORE
  INSERT ON  T_CAMPAIGNS FOR EACH ROW        WHEN (NEW.CAMPAIGN_ID IS NULL) BEGIN :NEW.CAMPAIGN_ID :=  CAMPAIGN_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."T_CAMPAIGNS_CAMPAIGN_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_COMPANIES_ID_COMPANY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."T_COMPANIES_ID_COMPANY_TRG" BEFORE
  INSERT ON  CAT_CLIENT FOR EACH ROW        WHEN (NEW.ID_COMPANY IS NULL) BEGIN :NEW.ID_COMPANY :=  COMPANY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."T_COMPANIES_ID_COMPANY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_USERS_USER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOLINF"."T_USERS_USER_ID_TRG" BEFORE
  INSERT ON  T_USERS FOR EACH ROW        WHEN (NEW.USER_ID IS NULL) BEGIN :NEW.USER_ID :=  USER_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BOLINF"."T_USERS_USER_ID_TRG" ENABLE;
