package com.twobig.sivale.bd.to;
//Generated 14/12/2015 12:03:39 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * CatClassificationCampaigns generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "cat_classification_campaigns", catalog = "lealtad_schema")
public class CatClassificationCampaign implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4703036863978770613L;
	private Integer catClassificationCampaignsId;
	private Integer catClassificationCampaignsIdParent;
	private CatView catViews;
	private String className;
	private String description;
	private Integer level;
	private Integer companyId;

	public static final String FIELD_CAT_CLASSIFICATION_ID = "catClassificationCampaignsId";
	public static final String FIELD_CAT_CLASSIFICATION_LEVEL = "level";
	public static final String FIELD_CAT_CLASSIFICATION_ID_PARENT = "catClassificationCampaignsIdParent";
	public static final String FIELD_CAT_COMPANY_ID = "companyId";

	@Id @GeneratedValue(strategy=IDENTITY)

	@Column(name = "cat_classification_campaigns_id", unique = true, nullable = false)
	public Integer getCatClassificationCampaignsId() {
		return this.catClassificationCampaignsId;
	}

	public void setCatClassificationCampaignsId(Integer catClassificationCampaignsId) {
		this.catClassificationCampaignsId = catClassificationCampaignsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fk_view")
	public CatView getCatViews() {
		return this.catViews;
	}

	public void setCatViews(CatView catViews) {
		this.catViews = catViews;
	}

	@Column(name = "class_name", nullable = false, length = 45)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "level", nullable = false)
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "parent_classification_id")
	public Integer getCatClassificationCampaignsIdParent() {
		return catClassificationCampaignsIdParent;
	}

	public void setCatClassificationCampaignsIdParent(Integer catClassificationCampaignsIdParent) {
		this.catClassificationCampaignsIdParent = catClassificationCampaignsIdParent;
	}
	
	@Column(name = "fk_company", nullable = false)
	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Override
	public String toString() {
		return "CatClassificationCampaign [catClassificationCampaignsId=" + catClassificationCampaignsId
				+ ", catClassificationCampaignsIdParent=" + catClassificationCampaignsIdParent + ", className="
				+ className + ", description=" + description + ", level=" + level + "]";
	}
}