package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatProfiles generated by hbm2java
 */
@Entity
@Table(name="cat_profiles"
    ,catalog="lealtad_schema"
)
public class CatProfile  implements java.io.Serializable {


     private int profileId;
     private String profile;
     private String comments;

    public CatProfile() {
    }

	
    public CatProfile(int profileId) {
        this.profileId = profileId;
    }
    public CatProfile(int profileId, String profile, String comments) {
       this.profileId = profileId;
       this.profile = profile;
       this.comments = comments;
    }
   
     @Id 

    
    @Column(name="profile_id", unique=true, nullable=false)
    public int getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }

    
    @Column(name="profile", length=50)
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }

    
    @Column(name="comments", length=50)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }


}


