package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import com.google.common.base.MoreObjects;

/**
 * CatProfiles generated by hbm2java
 */
@Entity
@Table(name="cat_profiles"
    ,catalog="lealtad_schema"
)
public class CatProfile  implements java.io.Serializable {


	private static final long serialVersionUID = 8196306852102371390L;
	private int profileId;
     private String profile;
     private String comments;
     
     public static final String PROFILE_FIELD_CAT_PROFILE_ID = "profileId";
   
     @Id 

    
    @Column(name="profile_id", unique=true, nullable=false)
    public int getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }

    
    @Column(name="profile", length=50)
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }

    
    @Column(name="comments", length=50)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("profileId", profileId).add("profile", profile)
				.add("comments", comments).toString();
	}
    
    

}


