package com.twobig.sivale.bd.to;
//Generated 14/12/2015 04:17:44 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatPublicationUser generated by hbm2java
 */
@Entity
@Table(name = "cat_publication_user")
public class CatPublicationUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1066749819972430137L;
	
	private String data;
	private int publicationId;
	private int userId;
	
	public static final String FIELD_USER_ID = "userId";
	public static final String FIELD_PUBLICATION_ID = "publicationId";
	
	
	@Column(name = "data", nullable = false, length = 1000)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}
	
	@Id
	@Column(name = "publication_id", unique = true, nullable = false)
	public int getPublicationId() {
		return publicationId;
	}

	public void setPublicationId(int publicationId) {
		this.publicationId = publicationId;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		return "CatPublicationUser [data=" + data + ", publicationId=" + publicationId + ", userId=" + userId + "]";
	}
	
	
	
}