package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import com.google.common.base.MoreObjects;

/**
 * CatViews generated by hbm2java
 */
@Entity
@Table(name = "cat_views", catalog = "lealtaddb")
public class CatView implements java.io.Serializable {

	private static final long serialVersionUID = -930953252733909619L;
	private Integer catViewId;
	private String colors;
	private String logos;
	private String messages;

	public CatView() {
	}

	@Id

	@Column(name = "cat_view_id", unique = true, nullable = false)
	public Integer getCatViewId() {
		return this.catViewId;
	}

	public void setCatViewId(Integer catViewId) {
		this.catViewId = catViewId;
	}

	@Column(name = "colors", length = 100)
	public String getColors() {
		return this.colors;
	}

	public void setColors(String colors) {
		this.colors = colors;
	}

	@Column(name = "logos", length = 300)
	public String getLogos() {
		return this.logos;
	}

	public void setLogos(String logos) {
		this.logos = logos;
	}

	@Column(name = "messages", length = 300)
	public String getMessages() {
		return this.messages;
	}

	public void setMessages(String messages) {
		this.messages = messages;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("catViewId", catViewId).add("colors", colors).add("logos", logos)
				.add("messages", messages).toString();
	}
}
