package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCompanies generated by hbm2java
 */
@Entity
@Table(name="t_companies"
    ,catalog="lealtad_schema"
)
public class TCompany  implements java.io.Serializable {


     private int idCompany;
     private String name;
     private String description;

    public TCompany() {
    }

	
    public TCompany(int idCompany, String name) {
        this.idCompany = idCompany;
        this.name = name;
    }
    public TCompany(int idCompany, String name, String description) {
       this.idCompany = idCompany;
       this.name = name;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id_company", unique=true, nullable=false)
    public int getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(int idCompany) {
        this.idCompany = idCompany;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


