package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPublications generated by hbm2java
 */
@Entity
@Table(name="t_publications"
    ,catalog="lealtad_schema"
)
public class TPublication  implements java.io.Serializable {


     private int publicationId;
     private TCampaign TCampaigns;
     private Date publishedDate;
     private String name;
     private String templateFilePath;
     private byte[] templateFileBlob;
     private String dataFilePath;
     private String dataFilePage;
     private byte[] dataFileBlob;

    public TPublication() {
    }

	
    public TPublication(int publicationId, TCampaign TCampaigns) {
        this.publicationId = publicationId;
        this.TCampaigns = TCampaigns;
    }
    public TPublication(int publicationId, TCampaign TCampaigns, Date publishedDate, String name, String templateFilePath, byte[] templateFileBlob, String dataFilePath, String dataFilePage, byte[] dataFileBlob) {
       this.publicationId = publicationId;
       this.TCampaigns = TCampaigns;
       this.publishedDate = publishedDate;
       this.name = name;
       this.templateFilePath = templateFilePath;
       this.templateFileBlob = templateFileBlob;
       this.dataFilePath = dataFilePath;
       this.dataFilePage = dataFilePage;
       this.dataFileBlob = dataFileBlob;
    }
   
     @Id 

    
    @Column(name="publication_id", unique=true, nullable=false)
    public int getPublicationId() {
        return this.publicationId;
    }
    
    public void setPublicationId(int publicationId) {
        this.publicationId = publicationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_campaign", nullable=false)
    public TCampaign getTCampaigns() {
        return this.TCampaigns;
    }
    
    public void setTCampaigns(TCampaign TCampaigns) {
        this.TCampaigns = TCampaigns;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="published_date", length=19)
    public Date getPublishedDate() {
        return this.publishedDate;
    }
    
    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="template_file_path", length=45)
    public String getTemplateFilePath() {
        return this.templateFilePath;
    }
    
    public void setTemplateFilePath(String templateFilePath) {
        this.templateFilePath = templateFilePath;
    }

    
    @Column(name="template_file_blob")
    public byte[] getTemplateFileBlob() {
        return this.templateFileBlob;
    }
    
    public void setTemplateFileBlob(byte[] templateFileBlob) {
        this.templateFileBlob = templateFileBlob;
    }

    
    @Column(name="data_file_path", length=45)
    public String getDataFilePath() {
        return this.dataFilePath;
    }
    
    public void setDataFilePath(String dataFilePath) {
        this.dataFilePath = dataFilePath;
    }

    
    @Column(name="data_file_page", length=45)
    public String getDataFilePage() {
        return this.dataFilePage;
    }
    
    public void setDataFilePage(String dataFilePage) {
        this.dataFilePage = dataFilePage;
    }

    
    @Column(name="data_file_blob")
    public byte[] getDataFileBlob() {
        return this.dataFileBlob;
    }
    
    public void setDataFileBlob(byte[] dataFileBlob) {
        this.dataFileBlob = dataFileBlob;
    }


}


