package com.twobig.sivale.bd.to;
// Generated 20/11/2015 02:09:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * TUsers generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "t_users", catalog = "bolinf")
public class TUser implements java.io.Serializable {

	private static final long serialVersionUID = 491334447509871158L;
	private Integer userId;
	private int catProfile;
	private int company;
	private String userLogin;
	private String password;
	private String email;

	private String fullName;
	private String firstName;
	private String lastName1;
	private String lastName2;

	private String tjCardNumber;
	private String tjAccountNumber;
	private String tjEmployer;
	private String tjOrigin;
	private String tjCardType;
	private String tjProduct;
	private String tjReference;
	private String tjAccountStatus;
	private String tjCardStatus;
	
	//user load
	private String tjBid;
	private String tjRazonSocial;
	private String tjStars;
	private String tjEcaps;
	private Boolean tjIdentificacion; 
	private Boolean tjAcuseFordLincoln;
	private Boolean tjInscritoEnPrograma;
	private Boolean tjAcuseFordCredit;
	private Boolean tjCarta_doble_perfil;
	private Integer tj_codigo_procedencia;
	private String tjComentarios;
	private String tjEstatusGeneral; 

	public static final String FIELD_USER_ID 				= "userId";
	public static final String FIELD_USER_FIRST_NAME 		= "firstName";
	public static final String FIELD_USER_CARD_NUMBER 		= "tjCardNumber";
	public static final String FIELD_USER_USER 				= "userLogin";
	public static final String FIELD_USER_PASS 				= "password";
	public static final String FIELD_USER_COMPANY 			= "tCompany";
	public static final String FIELD_USER_CAT_PROFILE 		= "catProfile";
	public static final String FIELD_USER_ACCOUNT_NUMBER 	= "tjAccountNumber";
	public static final String FIELD_USER_STARS 			= "tjStars";

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_id")
	@SequenceGenerator(name = "user_id", sequenceName = "USER_SEQ", initialValue = 0, allocationSize = 0)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_login", nullable = false, length = 45)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "full_name", length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name_1", length = 45)
	public String getLastName1() {
		return this.lastName1;
	}

	public void setLastName1(String lastName1) {
		this.lastName1 = lastName1;
	}

	@Column(name = "last_name_2", length = 45)
	public String getLastName2() {
		return this.lastName2;
	}

	public void setLastName2(String lastName2) {
		this.lastName2 = lastName2;
	}

	@Column(name = "tj_card_number", length = 45)
	public String getTjCardNumber() {
		return this.tjCardNumber;
	}

	public void setTjCardNumber(String tjCardNumber) {
		this.tjCardNumber = tjCardNumber;
	}

	@Column(name = "tj_account_number", length = 45)
	public String getTjAccountNumber() {
		return this.tjAccountNumber;
	}

	public void setTjAccountNumber(String tjAccountNumber) {
		this.tjAccountNumber = tjAccountNumber;
	}

	@Column(name = "tj_employer", length = 45)
	public String getTjEmployer() {
		return this.tjEmployer;
	}

	public void setTjEmployer(String tjEmployer) {
		this.tjEmployer = tjEmployer;
	}

	@Column(name = "tj_origin", length = 45)
	public String getTjOrigin() {
		return this.tjOrigin;
	}

	public void setTjOrigin(String tjOrigin) {
		this.tjOrigin = tjOrigin;
	}

	@Column(name = "tj_card_type", length = 45)
	public String getTjCardType() {
		return this.tjCardType;
	}

	public void setTjCardType(String tjCardType) {
		this.tjCardType = tjCardType;
	}

	@Column(name = "tj_product", length = 45)
	public String getTjProduct() {
		return this.tjProduct;
	}

	public void setTjProduct(String tjProduct) {
		this.tjProduct = tjProduct;
	}

	@Column(name = "tj_reference", length = 45)
	public String getTjReference() {
		return this.tjReference;
	}

	public void setTjReference(String tjReference) {
		this.tjReference = tjReference;
	}

	@Column(name = "tj_account_status", length = 45)
	public String getTjAccountStatus() {
		return this.tjAccountStatus;
	}

	public void setTjAccountStatus(String tjAccountStatus) {
		this.tjAccountStatus = tjAccountStatus;
	}

	@Column(name = "tj_card_status", length = 45)
	public String getTjCardStatus() {
		return this.tjCardStatus;
	}

	public void setTjCardStatus(String tjCardStatus) {
		this.tjCardStatus = tjCardStatus;
	}

	@Column(name = "fk_profile", nullable = false)
	public int getCatProfile() {
		return this.catProfile;
	}

	public void setCatProfile(int catProfile) {
		this.catProfile = catProfile;
	}

	@Column(name = "fk_company", nullable = false)
	public int getCompany() {
		return this.company;
	}

	public void setCompany(int company) {
		this.company = company;
	}
	
	@Column(name = "TJ_BID")
	public String getTjBid() {
		return tjBid;
	}

	public void setTjBid(String tjBid) {
		this.tjBid = tjBid;
	}

	@Column(name = "TJ_RAZON_SOCIAL")
	public String getTjRazonSocial() {
		return tjRazonSocial;
	}

	public void setTjRazonSocial(String tjRazonSocial) {
		this.tjRazonSocial = tjRazonSocial;
	}

	@Column(name = "TJ_STARS")
	public String getTjStars() {
		return tjStars;
	}

	public void setTjStars(String tjStars) {
		this.tjStars = tjStars;
	}

	@Column(name = "TJ_ECAPS")
	public String getTjEcaps() {
		return tjEcaps;
	}

	public void setTjEcaps(String tjEcaps) {
		this.tjEcaps = tjEcaps;
	}

	@Column(name = "TJ_IDENTIFICACION")
	public Boolean getTjIdentificacion() {
		return tjIdentificacion;
	}

	public void setTjIdentificacion(Boolean tjIdentificacion) {
		this.tjIdentificacion = tjIdentificacion;
	}

	@Column(name = "TJ_ACUSE_FORD_LINCOLN")
	public Boolean getTjAcuseFordLincoln() {
		return tjAcuseFordLincoln;
	}

	public void setTjAcuseFordLincoln(Boolean tjAcuseFordLincoln) {
		this.tjAcuseFordLincoln = tjAcuseFordLincoln;
	}

	@Column(name = "TJ_INSCRITO_EN_PROGRAMA")
	public Boolean getTjInscritoEnPrograma() {
		return tjInscritoEnPrograma;
	}

	public void setTjInscritoEnPrograma(Boolean tjInscritoEnPrograma) {
		this.tjInscritoEnPrograma = tjInscritoEnPrograma;
	}

	@Column(name = "TJ_ACUSE_FORD_CREDIT")
	public Boolean getTjAcuseFordCredit() {
		return tjAcuseFordCredit;
	}

	public void setTjAcuseFordCredit(Boolean tjAcuseFordCredit) {
		this.tjAcuseFordCredit = tjAcuseFordCredit;
	}

	@Column(name = "TJ_CARTA_DOBLE_PERFIL")
	public Boolean getTjCarta_doble_perfil() {
		return tjCarta_doble_perfil;
	}

	public void setTjCarta_doble_perfil(Boolean tjCarta_doble_perfil) {
		this.tjCarta_doble_perfil = tjCarta_doble_perfil;
	}

	@Column(name = "TJ_CODIGO_PROCEDENCIA")
	public Integer getTj_codigo_procedencia() {
		return tj_codigo_procedencia;
	}

	public void setTj_codigo_procedencia(Integer tj_codigo_procedencia) {
		this.tj_codigo_procedencia = tj_codigo_procedencia;
	}

	@Column(name = "TJ_COMENTARIOS")
	public String getTjComentarios() {
		return tjComentarios;
	}

	public void setTjComentarios(String tjComentarios) {
		this.tjComentarios = tjComentarios;
	}
	
	@Column(name = "TJ_ESTATUS_GENERAL")
	public String getTjEstatusGeneral() {
		return tjEstatusGeneral;
	}

	public void setTjEstatusGeneral(String tjEstatusGeneral) {
		this.tjEstatusGeneral = tjEstatusGeneral;
	}
	
	@Override
	public String toString() {
		return "TUser [userId=" + userId + ", catProfile=" + catProfile + ", company=" + company + ", userLogin="
				+ userLogin + ", password=" + password + ", email=" + email + ", fullName=" + fullName + ", firstName="
				+ firstName + ", lastName1=" + lastName1 + ", lastName2=" + lastName2 + ", tjCardNumber=" + tjCardNumber
				+ ", tjAccountNumber=" + tjAccountNumber + ", tjEmployer=" + tjEmployer + ", tjOrigin=" + tjOrigin
				+ ", tjCardType=" + tjCardType + ", tjProduct=" + tjProduct + ", tjReference=" + tjReference
				+ ", tjAccountStatus=" + tjAccountStatus + ", tjCardStatus=" + tjCardStatus + ", tjBid=" + tjBid
				+ ", tjRazonSocial=" + tjRazonSocial + ", tjStars=" + tjStars + ", tjEcaps=" + tjEcaps
				+ ", tjIdentificacion=" + tjIdentificacion + ", tjAcuseFordLincoln=" + tjAcuseFordLincoln
				+ ", tjInscritoEnPrograma=" + tjInscritoEnPrograma + ", tjAcuseFordCredit=" + tjAcuseFordCredit
				+ ", tjCarta_doble_perfil=" + tjCarta_doble_perfil + ", tj_codigo_procedencia=" + tj_codigo_procedencia
				+ ", tjComentarios=" + tjComentarios + ", tjEstatusGeneral=" + tjEstatusGeneral + "]";
	}
}
